from selenium import webdriver
from configExcel import URL
from selenium.webdriver.common.by import By

driver = webdriver.Chrome()
driver.get(URL)

driver.find_element(By.CSS_SELECTOR, '[name="search_query"]').send_keys('Valor a ingresar')
driver.find_element(By.CSS_SELECTOR, '.ytp-share-panel-include-playlist-checkbox').send_keys('Valor a ingresar')
driver.find_element(By.CSS_SELECTOR, '#button').click()
driver.find_element(By.CSS_SELECTOR, '.yt-spec-button-shape-next.yt-spec-button-shape-next--tonal.yt-spec-button-shape-next--mono.yt-spec-button-shape-next--size-m.yt-spec-button-shape-next--enable-backdrop-filter-experiment').click()
driver.find_element(By.CSS_SELECTOR, '.yt-spec-button-shape-next.yt-spec-button-shape-next--text.yt-spec-button-shape-next--mono.yt-spec-button-shape-next--size-m.yt-spec-button-shape-next--icon-only-default.yt-spec-button-shape-next--enable-backdrop-filter-experiment').click()
driver.find_element(By.CSS_SELECTOR, '#search-icon-legacy').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-playlist-menu-button.ytp-button.ytp-playlist-menu-button-tiny').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-button.ytp-search-button').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-button.ytp-cards-button').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-button.ytp-overflow-button').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-unmute.ytp-popup.ytp-button.ytp-unmute-animated.ytp-unmute-shrink').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-gated-actions-overlay-miniplayer-close-button.ytp-button').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-suggested-action-badge-dismiss-button-icon.ytp-button').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-featured-product-overflow-icon.ytp-button').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-large-play-button.ytp-button').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-featured-product-info-icon.ytp-button').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-button.ytp-suggested-action-badge.ytp-suggested-action-badge-with-controls.ytp-suggested-action-badge-expanded').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-button.ytp-suggested-action-badge.ytp-suggested-action-badge-with-controls').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-button.ytp-mdx-privacy-popup-cancel').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-button.ytp-mdx-privacy-popup-confirm').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-playlist-menu-close.ytp-button').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-share-panel-close.ytp-button').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-watch-later-button.ytp-button').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-button.ytp-share-button').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-button.ytp-copylink-button').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-overflow-panel-close.ytp-button').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-play-button.ytp-button').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-mute-button.ytp-button').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-live-badge.ytp-button').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-chapter-title.ytp-button.ytp-chapter-container-disabled').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-fullerscreen-edu-button.ytp-button').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-button').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-subtitles-button.ytp-button').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-button.ytp-settings-button').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-miniplayer-button.ytp-button').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-pip-button.ytp-button').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-size-button.ytp-button').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-remote-button.ytp-button').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-fullscreen-button.ytp-button').click()

driver.quit()