from selenium import webdriver
from selenium.webdriver.common.by import By

driver = webdriver.Chrome()
driver.get('https://www.youtube.com/?app=desktop&hl=es')

driver.find_element(By.CSS_SELECTOR, '[name="search_query"]').send_keys('Valor a ingresar')
driver.find_element(By.CSS_SELECTOR, '.ytp-share-panel-include-playlist-checkbox').send_keys('Valor a ingresar')
driver.find_element(By.CSS_SELECTOR, '#button').click()
driver.find_element(By.CSS_SELECTOR, '.yt-spec-button-shape-next.yt-spec-button-shape-next--tonal.yt-spec-button-shape-next--mono.yt-spec-button-shape-next--size-m.yt-spec-button-shape-next--enable-backdrop-filter-experiment').click()
driver.find_element(By.CSS_SELECTOR, '.yt-spec-button-shape-next.yt-spec-button-shape-next--text.yt-spec-button-shape-next--mono.yt-spec-button-shape-next--size-m.yt-spec-button-shape-next--icon-only-default.yt-spec-button-shape-next--enable-backdrop-filter-experiment').click()
driver.find_element(By.CSS_SELECTOR, '#search-icon-legacy').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-playlist-menu-button.ytp-button.ytp-playlist-menu-button-tiny').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-button.ytp-search-button').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-button.ytp-cards-button').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-button.ytp-overflow-button').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-unmute.ytp-popup.ytp-button.ytp-unmute-animated.ytp-unmute-shrink').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-gated-actions-overlay-miniplayer-close-button.ytp-button').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-suggested-action-badge-dismiss-button-icon.ytp-button').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-featured-product-overflow-icon.ytp-button').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-large-play-button.ytp-button').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-featured-product-info-icon.ytp-button').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-button.ytp-suggested-action-badge.ytp-suggested-action-badge-with-controls.ytp-suggested-action-badge-expanded').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-button.ytp-suggested-action-badge.ytp-suggested-action-badge-with-controls').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-button.ytp-mdx-privacy-popup-cancel').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-button.ytp-mdx-privacy-popup-confirm').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-playlist-menu-close.ytp-button').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-share-panel-close.ytp-button').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-watch-later-button.ytp-button').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-button.ytp-share-button').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-button.ytp-copylink-button').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-overflow-panel-close.ytp-button').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-play-button.ytp-button').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-mute-button.ytp-button').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-live-badge.ytp-button').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-chapter-title.ytp-button.ytp-chapter-container-disabled').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-fullerscreen-edu-button.ytp-button').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-button').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-subtitles-button.ytp-button').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-button.ytp-settings-button').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-miniplayer-button.ytp-button').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-pip-button.ytp-button').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-size-button.ytp-button').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-remote-button.ytp-button').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-fullscreen-button.ytp-button').click()
driver.find_element(By.CSS_SELECTOR, '.style-scope.ytd-miniplayer').click()
driver.find_element(By.CSS_SELECTOR, '#thumbnail').click()
driver.find_element(By.CSS_SELECTOR, '#thumbnail').click()
driver.find_element(By.CSS_SELECTOR, '#logo').click()
driver.find_element(By.CSS_SELECTOR, '.yt-simple-endpoint.style-scope.ytd-topbar-menu-button-renderer').click()
driver.find_element(By.CSS_SELECTOR, '.yt-spec-button-shape-next.yt-spec-button-shape-next--outline.yt-spec-button-shape-next--call-to-action.yt-spec-button-shape-next--size-m.yt-spec-button-shape-next--icon-leading.yt-spec-button-shape-next--enable-backdrop-filter-experiment').click()
driver.find_element(By.CSS_SELECTOR, '#logo').click()
driver.find_element(By.CSS_SELECTOR, '#endpoint').click()
driver.find_element(By.CSS_SELECTOR, '#endpoint').click()
driver.find_element(By.CSS_SELECTOR, '#endpoint').click()
driver.find_element(By.CSS_SELECTOR, '#endpoint').click()
driver.find_element(By.CSS_SELECTOR, '#endpoint').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-title-channel-logo').click()
driver.find_element(By.CSS_SELECTOR, '/div#movie_player/div:nth-of-type(3)/div:nth-of-type(1)/div:nth-of-type(2)/div:nth-of-type(1)/div:nth-of-type(1)/a:nth-of-type(1)').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-title-link.yt-uix-sessionlink.ytp-title-fullerscreen-link').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-title-channel-name').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-suggested-action-container').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-paid-content-overlay-link').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-featured-product-container').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-playlist-menu-title-name').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-share-panel-link.ytp-no-contextmenu').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-prev-button.ytp-button').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-next-button.ytp-button').click()
driver.find_element(By.CSS_SELECTOR, '.yt-simple-endpoint.style-scope.ytd-video-owner-renderer').click()
driver.find_element(By.CSS_SELECTOR, '.yt-simple-endpoint.style-scope.ytd-video-primary-info-renderer').click()
driver.find_element(By.CSS_SELECTOR, '#media-container-link').click()
driver.find_element(By.CSS_SELECTOR, '#thumbnail').click()
driver.find_element(By.CSS_SELECTOR, '.style-scope.ytd-yoodle-renderer').click()
driver.find_element(By.CSS_SELECTOR, '.style-scope.ytd-yoodle-renderer').click()
driver.find_element(By.CSS_SELECTOR, '#img').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-suggested-action-badge-img').click()
driver.find_element(By.CSS_SELECTOR, '/div#movie_player/div:nth-of-type(15)/div:nth-of-type(1)/div:nth-of-type(2)/a:nth-of-type(1)/div:nth-of-type(1)/img:nth-of-type(1)').click()
driver.find_element(By.CSS_SELECTOR, '#img').click()
driver.find_element(By.CSS_SELECTOR, '.miniplayer.style-scope.ytd-miniplayer').click()
driver.find_element(By.CSS_SELECTOR, '#player-container').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-bezel').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-mdx-popup-dialog').click()
driver.find_element(By.CSS_SELECTOR, '#ytp-id-22').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-playlist-menu-items').click()
driver.find_element(By.CSS_SELECTOR, '#ytp-id-25').click()
driver.find_element(By.CSS_SELECTOR, '#ytp-id-29').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-panel-menu').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-progress-bar').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-fine-scrubbing-thumbnails').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-fine-scrubbing-play').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-fine-scrubbing-dismiss').click()
driver.find_element(By.CSS_SELECTOR, '.ytp-volume-panel').click()

driver.quit()